### ISSUE TITLE
View Recent

### ISSUE THREAD

**Issue by falcons52** [bravecollective/forums#22]
Make a section of the forums that lets me see what content I haven't viewed yet.

**Comment by lizthegrey** [comment]
Does this include only chronological ordering by most recent comment, or does this also include read status tracking?

**Comment by falcons52** [comment]
The forums should have the ability to display whether or not you have viewed a thread and update when people post new comments.

**Comment by amcgregor** [comment]
My initial thoughts on this would be to include a MappingField mapping thread IDs to datetime objects in each user.  Any thread not present there has never been viewed (new), and any thread that is present but has a date older than the modification time of a thread has been updated since last viewing.  Updating that value should be a simple `set__threadid=utcnow()` atomic update upon viewing a thread.

To support "mark everything as read" we'd also want a per-user "last marked everything read" time, allowing the per-thread mapping to get cleared.

Edited to add: I was going to style this using cell background colours in the forum index and using the background around the profile image (padding between drop-shadow border and image).

**Comment by jboning** [comment]
I think I'm going to take this on. I want to use a DictField that looks like the following:

```
# { forum1: forum1_read_ts,
#   forum2: {
#       thread1: thread1_read_ts,
#       thraed2: thread2_read_ts,
#   }
# }
```

This should make it faster and cleaner to mark a forum as read, as we won't have to iterate over all the threads in the forum or that the user has seen.

If we want a "mark category as read" feature, it's probably okay to scan over those forums though, since the number of forums per category will be small.

If this seems like premature optimization (or otherwise sounds bad), let me know!

**Comment by amcgregor** [comment]
Wel, no, this sounds like a good idea if we also wish to be able to mark whole forums as read.  Note that we won't need to actually load all of this data on each request; you can use MongoDB quires to query key presence and value ranges, and select a subset of the document to use.

I see the following:

``` python
seen = {
    ObjectID("5308f56e6f692b1e659df586"): {
        ObjectID("5308f5fa6f692b1e659df588"): datetime(2014, 2, 16, 0, 51, 12),
    },
    ObjectID("5308f59c6f692b1e659df587"): {
        "seen": datetime(2014, 2, 16, 0, 51, 12)
    },
}
```

The first is an example of a forum that has never been marked as wholly read with one thread that has been read as of X date.  The second is a forum that has been completely marked as read as of date Y, a process that should also automatically remove any child values with a date less than the current date.

The a forum index would want to load up the first level, looking at a given thread would only need the seen and thread-specific keys from the forum sub-document.

The reason I keep the datatypes uniform is that we want atomic assignments to work.

**Comment by cdanis** [comment]
Just a remark: I'd love to see separate displays of both:
- All posts, ordered by post timestamp, regardless of read/unread status
- Unread posts, ordered by post timestamp

**Comment by amcgregor** [comment]
Should be easy enough to add a data attribute to each table row and use some fancy JS to animate and filter the results.
