### ISSUE TITLE
Marking an empty subforum as read breaks things

### ISSUE THREAD

**Issue by cdanis** [bravecollective/forums#40]
With the new unread support (which is awesome, btw), one can do the following:
- Create an entirely empty sub-forum, with no discussions in it
- Mark that forum as read

Now, browsing to the dashboard page will consistently return HTTP 500s.

One can work around this by remembering the URL path of that empty subforum, and browsing to it and starting a discussion.

**Comment by cdanis** [comment]
BTW: I attempted to mark this empty section as read in the first place because an empty section shows up with the 'unread' highlight color on the dashboard.

**Comment by ikanobori** [comment]
Seems to be pertaining to here:

https://github.com/eve-val/forums/blob/caf7ee979c176b983ea8aeab2e24176d295c325c/brave/forums/auth/model.py#L127

(if there are no threads there is also no threads[0])

with regards to your first question. The second part seems to be related to the fact that a forum isn't marked as read unless it has been accessed, seen here:

https://github.com/eve-val/forums/blob/caf7ee979c176b983ea8aeab2e24176d295c325c/brave/forums/auth/model.py#L122

Which is why the forum is never set read here:

https://github.com/eve-val/forums/blob/caf7ee979c176b983ea8aeab2e24176d295c325c/brave/forums/auth/model.py#L142

I'd put this in a pull request but I don't currently have a development environment set up.

**Comment by jboning** [comment]
Whoops, my bad. Pull request issued.
